// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jivkniqvqfxrqqoekwbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppdmtuaXF2cWZ4cnFxb2Vrd2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NzA2MzksImV4cCI6MjA1NjE0NjYzOX0.dbrQAL5Vsnp9eYKPTjj9J3l5ioB0Y9Nzfoq2K4U1hA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);